added views/urls
Della955/StableMate pull request #6
Opened 2023-08-10 22:05 UTC by Della955

still working on adding in the last views / urls to a few more of my apps but majority is done

2023-08-11 08:49 UTC, fravila08 requested changes

2023-08-11 08:49 UTC, fravila08 commented on list_app/views.py
> +class Select_list(APIView):
Hey Della is it possible to utilize inheritance to manage your permission classes so you won't have to repeat yourself.
```python
class WithPermissions(APIView):
  authentication_classes = [TokenAuthentication]
  permission_classes = [IsAuthenticated]

class All_lists(WithPermissions):
  def get(self, request):
    pass
``` 
This way you can follow better dry concepts

2023-08-11 08:49 UTC, fravila08 commented on stableMate/lib/python3.11/site-packages/django/template/loaders/__pycache__/__init__.cpython-311.pyc
It looks like you didn't add `__pycache__` directories to your gitignore. Please use the Python gitignore documentation to update your gitignore to avoid files like these to be pushed onto github.

2023-08-11 08:49 UTC, fravila08 commented on stableMate/lib/python3.11/site-packages/django/__pycache__/shortcuts.cpython-311.pyc
It looks like your venv is also within your git repository please remove this venv from git and github

2023-08-11 08:49 UTC, fravila08 commented on stable_app/views.py
> +    def put(self, request, stable_id):
It may be good to add some error handling to your views

2023-08-11 14:04 UTC, Della955 commented on stableMate/lib/python3.11/site-packages/django/template/loaders/__pycache__/__init__.cpython-311.pyc
Yeah I have those added to my file so I'm not sure why they keeping being pushed.

2023-08-11 14:07 UTC, Della955 reviewed
will update with comments

2023-08-14 02:07 UTC, fravila08 approved these changes

2023-08-14 12:41 UTC, merged